// export const selectedPhrases = [
//   'did you see that spectacular explosion',
//   'keep receipts for all your expenses',
//   'February has an extra day',
//   'the kids are very excited',
//   'no exchange without a bill',
//   'zero in on the facts',
//   'the hopes of a new organization',
//   'Valium in the economy size',
//   'three two one zero blast off',
//   'these cookies are so amazing',
//   'one heck of a question',
//   'do not squander your time',
//   'not quite so smart as you think',
//   'frequently asked questions',
//   'that is a very odd question',
//   'her majesty visited our country',
//   'the dow jones index has risen',
//   'a good joke deserves a good laugh',
//   'he is just like everyone else',
//   'I am wearing a tie and a jacket',
//   'I like to play tennis',
//   'tickets are very expensive',
//   'you must be getting old',
//   'apartments are too expensive',
//   'that is very unfortunate',
//   'communicate through email',
//   'they love to yap about nothing',
//   'relations are very strained',
//   'accompanied by an adult',
//   'a security force of eight thousand',
//   'longer than a football field',
//   'rectangular objects have four sides',
//   'no kissing in the library',
//   'seasoned golfers love the game',
//   'prevailing wind from the east',
//   'mom made her a turtleneck',
//   'please take a bath this month',
//   'the collapse of the Roman empire',
//   'work hard to reach the summit',
//   'historic meeting without a result'
// ];

// for b
// export const selectedPhrases = [
//   'drugs should be avoided',
//   'no exchange without a bill',
//   'February has an extra day',
//   'elections bring out the best',
//   'the presidential suite is very busy',
//   'learn to walk before you run',
//   'I cannot believe I ate the whole thing',
//   'goldilocks and the three bears',
//   'the biggest hamburger I have ever seen',
//   'the fax machine is broken',
//   'reading week is just about here',
//   'would you like to come to my house',
//   'we accept personal checks',
//   'do you get nervous when you speak',
//   'I like baroque and classical music',
//   'acutely aware of her good looks',
//   'we run the risk of failure',
//   'the stock exchange dipped',
//   'he is just like everyone else',
//   'chemical spill took forever'
// ];

// export const selectedPhrases = [
//   'February has an extra day',
//   'apartments are too expensive',
//   'tickets are very expensive',
//   'experience is hard to come by',
//   'presidents drive expensive cars',
//   'express delivery is very fast',
//   'no exchange without a bill',
//   'a fox is a very smart animal',
//   'the coronation was very exciting',
//   'dinosaurs have been extinct for ages',
//   'three two one zero blast off',
//   'video camera with a zoom lens',
//   'I watched blazing saddles',
//   'these cookies are so amazing',
//   'go out for some pizza and beer',
//   'the fire blazed all weekend',
//   'labour unions know how to organize',
//   'zero in on the facts',
//   'the hopes of a new organization',
//   'Valium in the economy size',
//   'that is a very odd question',
//   'why do you ask silly questions',
//   'quick there is someone knocking',
//   'frequently asked questions',
//   'salesmen must make their monthly quota',
//   'a duck quacks to ask for food',
//   'your etiquette needs some work',
//   'that referendum asked a silly question',
//   'not quite so smart as you think',
//   'I like baroque and classical music',
//   'a good joke deserves a good laugh',
//   'watch out for low flying objects',
//   'I am wearing a tie and a jacket',
//   'try to enjoy your maternity leave',
//   'my favorite subject is psychology',
//   'an injustice is committed every day',
//   'he is just like everyone else',
//   'we are subjects and must obey',
//   'this leather jacket is too warm',
//   'good jobs for those with education'
// ];

export const selectedPhrases = [
  'Both fickle dwarves jinx my pig quiz',
  'Fat hag dwarves quickly zap jinx mob',
  'Hick dwarves jam blitzing foxy quip',
  'Fox dwarves chop my talking quiz job',
  'Public junk dwarves quiz mighty fox',
  'Jack fox bids ivy strewn phlegm quiz',
  'How quickly daft jumping zebras vex',
  'Two driven jocks help fax my big quiz',
  'Fickle bog dwarves jinx empathy quiz',

  'The five boxing wizards jump quickly',
  'Pack my box with five dozen liquor jugs',
  'Cozy lummox gives smart squid who asks for job pen',
  'My faxed joke won a pager in the cable TV quiz show'
];
//   'Public junk dwarves hug my quartz fox',
//   'Jumping hay dwarves flock quartz box',
//   'Five jumping wizards hex bolty quick',
//   'Five hexing wizard bots jump quickly',
//   'Quick fox jumps nightly above wizard',
//   'Vamp fox held quartz duck just by wing'
// ];
